### PR TITLE
[RDPHOEN-1221] Applying Iris Coporate Design to SWUpdate webinterface

### PR DESCRIPTION
**Pull request by ThomasWNoack**

### CODE REVIEW

**Review by linkjumper — DISMISSED** [review]
The unpacked web content's origin seems to come from [swupdate/web-app/](https://github.com/sbabic/swupdate/tree/master/web-app) . There is a [manual](https://github.com/sbabic/swupdate/blob/master/doc/source/mongoose.rst), how to work with the web content. The current solution is problematic, because a single change in the packed oneliner, makes an easy patch rebase impossible. @Jasper-Ben  or @martin31821  s opinion is mandatory here.

My suggested solution would be to apply patches on swupdate/web-app/ and adapt the swupdate-www recipe to create the web-content from the origin location. Do you have better ideas than freezing the swupdate version?

**Review by Eximmius — COMMENTED** [review]
The update is working well. 
Two remarks:
1. A customer can upload a wrong update file, and the update starts automatically. This can be dangerous for several reasons and a Confirm button could avoid this. 
2. This page is quite different from the Web interface update page, from a customer point of view I would like similar layouts.
Should we plan this in development?

**Review by irisPHSC — APPROVED** [review]
the implementation itself lgtm.
how the changes are applied is a different story but i don't have an alternative atm.

**Review by Eximmius — APPROVED** [review]

**Comment by ThomasWNoack** [comment]
## Maintainer Checklist
- Is there a changelog entry? *Yes*
- Do the commit messages comply with the specifications? *Yes*
- Was a Jenkins run performed and was it error-free? *Yes*
- Is a manual rebase necessary? *yes, done*

**Pull request merged**
