### PR TITLE
Feature/ersc/rdphoen 1314 tc358746 fixes

### PR DESCRIPTION
**Pull request by iris-ersc**
This should fix (hopefully) all serializer flickering and striped frames bugs.

Replace previous patch. Details in patch description.

Pipeline run: 2283

### CODE REVIEW

**Review by jan-hannig — APPROVED** [review]

**Comment by linkjumper** [comment]
I would not pack the two dts files in a common patch file. If we were to remove imx8mp-evk support at some point, this patch file would have to be adjusted.

**Review by linkjumper — APPROVED** [review]
Tested with a tolerant developer IU! Further tests with an intolerant one would be helpful as well.

**Comment by iris-ersc** [comment]
I would split this into 3 patches:
- Driver code adjustments
- irma6r2 dts
- imx8mpevk dts

We might also use just one lane. Discussion is still going on.

**Comment by iris-ersc** [comment]
Patch is splitted. New pipeline: 2294

**Review by Eximmius — APPROVED** [review]
Frame End events: 146274
Frame Start events: 146274
CRC Error events: 0
ECC Error events: 0
:tada:

**Review by linkjumper — APPROVED** [review]
Tested again! No Errors!

**Comment by iris-ersc** [comment]
## Maintainer Checklist
- Is there a changelog entry? *Yes*
- Do the commit messages comply with the specifications? *Yes*
- Was a Jenkins run performed and was it error-free? *Yes*
- Is a manual rebase necessary? *no*

**Comment by jan-hannig** [comment]
Overnight-Test HDR-d Developer User Interface:

[22100.170109] mxc-mipi-csi2.0: fmt: 0x2013, 320 x 120
[22100.791856] epc660 1-0022: 00Mbps/Full - flow control rx/tx
[81988.263431] epc660 1ents: 4790998
[81988.276844] mxc-mipi-csi2.0: Frame Start events: 4790998
[81988.285014] mxc-mipi-csi2.0: Non-image data after odd frame events: 0
[81988.294312] mxc-mipi-csi2.0: Nots: 0
[81988.322553] mxc-mipi-csi2.0: Unknown Error events: 0
[81988.330375] mxc-mipi-csi2.0: CRC Error events: 0
[81988.337850] mxc-mipi-csi2.0: ECC Error events: 0
[81988.345325]53667] mxc-mipi-csi2.0: Lost Frame End Error events: 0
[81988.362098] mxc-mipi-csi2.0: Lost Frame Start Error events: 0
[81988.370700] mxc-mipi-csi2.0: SOT Error events: 0

**Pull request merged**
