### PR TITLE
Backport chrony 4.2 to firmware

### PR DESCRIPTION
**Pull request by Jasper-Ben**
NTS support has been added in 4.0: https://chrony.tuxfamily.org/news.html

### CODE REVIEW

**Comment by Jasper-Ben** [comment]
merge with https://github.com/iris-GmbH/iris-kas/pull/101

**Comment by DanielBaumgart** [comment]
Please link an Jira-Task to this. Ask R1-Team for Ticketnumber.

**Review by DanielBaumgart — APPROVED** [review]
Jenkinsrun (on-Prem)?

**Comment by Jasper-Ben** [comment]
> Please link an Jira-Task to this. Ask R1-Team for Ticketnumber.

done.

**Comment by Jasper-Ben** [comment]
> Jenkinsrun (on-Prem)?

done. http://jenkinsmaster.irisgmbh.local:8080/job/RD-V/job/IRMA6/job/Irma6Yocto_BuildFirmware.feature/1074/

**Review by ThomasWNoack — APPROVED** [review]

**Pull request merged**
