### PR TITLE
Feature/migl/rdphoen 1194 postupdate reboot

### PR DESCRIPTION
**Pull request by linkjumper**
swupdate: Add postupdate cmd: reboot

**Test**
```
root@imx8mpevk:~# ps
585 root      238m S    /usr/bin/swupdate -v -p 'reboot'  
```

### CODE REVIEW

**Comment by linkjumper** [comment]
Conflict resolved and rebased!

**Comment by sven-foerster** [comment]
**Test**

root@imx8mpevk:~# ps
...
  631 root      238m S    /usr/bin/swupdate -v -p 'reboot'
...

**Review by sven-foerster — APPROVED** [review]
**Test**

root@imx8mpevk:~# ps
...
  631 root      238m S    /usr/bin/swupdate -v -p 'reboot'
...

**Comment by jan-hannig** [comment]
Test:
root@imx8mp-irma6r2:~# ps
  PID USER       VSZ STAT COMMAND
    1 root      1932 S    init [5]
[...]
  592 avahi     3632 S    avahi-daemon: chroot helper
  596 root      238m S    /usr/bin/swupdate -v -p 'reboot'
  617 root      3440 S    {start_getty} /bin/sh /bin/start_getty 115200 ttymxc1 vt102
[...]
successful!

**Review by jan-hannig — APPROVED** [review]
Successfully tested on the irma6r2 Hardware.

**Comment by iris-ersc** [comment]
## Maintainer Checklist
- Is there a changelog entry? *Yes*
- Do the commit messages comply with the specifications? *Yes*
- Was a Jenkins run performed and was it error-free? *Yes*
- Is a manual rebase necessary? *already done*

**Pull request merged**
